name: build
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest]
    name: tests
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go get github.com/mfridman/tparse
          go test -v -race -cover -json ./... | $(go env GOPATH)/bin/tparse -all
  lint:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...
          go vet ./...
  coverage:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    name: coverage
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
